# Generated by Django 3.1 on 2020-08-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tetris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tetrisgamemodes',
            name='game_mode_name',
            field=models.CharField(default='Tetris Breh', max_length=120),
        ),
        migrations.AddField(
            model_name='tetrisgamemodes',
            name='selected_game_mode',
            field=models.TextField(default='Normal'),
        ),
        migrations.AddField(
            model_name='tetrisplayer',
            name='number_of_loses',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='tetrisplayer',
            name='number_of_wins',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='tetrisplayer',
            name='game_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='tetrisplayer',
            name='game_score',
            field=models.TextField(default='0'),
        ),
    ]
